[project]
name = "jetbrainsmonohangul"
version = "0.1.0"
description = "JetBrains Mono에 D2Coding의 한글 영역을 덧씌운 뒤 폭을 조정한 폰트입니다. Nerd Fonts도 릴리즈에 포함되어 있습니다."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "wget>=3.2",
]
